'use client'

import { useState, useMemo, useEffect } from 'react'
import { Search, ChevronDown, ChevronUp, Shield, AlertTriangle, Terminal, Wrench, Loader2 } from 'lucide-react'
import { useTranslation } from '@/lib/i18n'
import { getAgents } from '@/lib/api'
import type { AgentInfo } from '@/lib/types'

interface DocContent {
  label: string
  what: string
  risks: string[]
  verify: string[]
}

interface StaticDoc {
  agent: string
  category: string
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'
  mitre?: string[]
  tools?: string[]
  content: { es: DocContent; en: DocContent }
}

// ── Category defaults (fallback for agents without static docs) ───────────────

const CAT_DEFAULTS: Record<string, { mitre: string[]; tools: string[]; en: { risks: string[]; verify: string[] }; es: { risks: string[]; verify: string[] } }> = {
  analytics: {
    mitre: ['T1082 - System Information Discovery', 'T1057 - Process Discovery'],
    tools: ['Splunk', 'Elastic SIEM', 'IBM QRadar', 'Microsoft Sentinel'],
    en: { risks: ['Advanced threats missed by signature-based tools', 'Insider anomalies going undetected', 'Unknown attack patterns and zero-day activity'], verify: ['Review SIEM dashboards for baseline deviations', 'Run proactive threat-hunting queries on EDR logs', 'Compare current behavior against historical baseline'] },
    es: { risks: ['Amenazas avanzadas no detectadas por firmas', 'Anomalias internas sin alertas previas', 'Patrones de ataque desconocidos y actividad zero-day'], verify: ['Revisa dashboards del SIEM buscando desviaciones del baseline', 'Ejecuta hunts proactivos en logs del EDR', 'Compara comportamiento actual vs. baseline historico'] },
  },
  cloud: {
    mitre: ['T1078.004 - Cloud Accounts', 'T1530 - Data from Cloud Storage', 'T1190 - Exploit Public-Facing Application'],
    tools: ['Prowler', 'ScoutSuite', 'CloudMapper', 'AWS CLI', 'az CLI', 'gcloud'],
    en: { risks: ['Publicly exposed cloud resources (buckets, databases, APIs)', 'Overly permissive IAM roles with wildcard permissions', 'Misconfigured security groups or firewall rules'], verify: ['Run Prowler audit: prowler aws --region us-east-1', 'Check public resource exposure in resource configs', 'Review IAM policies for wildcard (*) actions or resources'] },
    es: { risks: ['Recursos cloud publicamente expuestos (buckets, bases de datos, APIs)', 'Roles IAM con permisos excesivos o wildcard', 'Security groups o reglas de firewall mal configuradas'], verify: ['Ejecuta auditoria con Prowler: prowler aws --region us-east-1', 'Verifica exposicion publica en configs de recursos', 'Revisa politicas IAM buscando acciones wildcard (*)'] },
  },
  compliance: {
    mitre: [],
    tools: ['OpenSCAP', 'Lynis', 'Nessus', 'Qualys'],
    en: { risks: ['Regulatory violations (GDPR, PCI-DSS, HIPAA, ISO27001)', 'Incomplete or tampered audit logs', 'Policy gaps and missing security controls'], verify: ['Run OpenSCAP: oscap oval eval --report report.html oval.xml', 'Verify log retention: find /var/log -mtime +90 | wc -l', 'Review password policy: cat /etc/login.defs | grep PASS'] },
    es: { risks: ['Violaciones regulatorias (GDPR, PCI-DSS, HIPAA, ISO27001)', 'Logs de auditoria incompletos o manipulados', 'Brechas en politicas y controles de seguridad faltantes'], verify: ['Ejecuta OpenSCAP: oscap oval eval --report report.html oval.xml', 'Verifica retencion de logs: find /var/log -mtime +90 | wc -l', 'Revisa politica de contrasenas: cat /etc/login.defs | grep PASS'] },
  },
  containers: {
    mitre: ['T1610 - Deploy Container', 'T1613 - Container and Resource Discovery', 'T1552.007 - Container API'],
    tools: ['Trivy', 'Falco', 'kube-bench', 'Docker Bench', 'Anchore'],
    en: { risks: ['Containers running as root or with privileged mode', 'Vulnerable base images deployed in production', 'Exposed container runtime APIs (Docker socket, kubelet)'], verify: ['Scan image: trivy image <image>:<tag>', 'Find privileged containers: docker inspect $(docker ps -q) | jq .[].HostConfig.Privileged', 'Check Docker socket exposure: ls -la /var/run/docker.sock'] },
    es: { risks: ['Contenedores ejecutandose como root o en modo privilegiado', 'Imagenes base con vulnerabilidades en produccion', 'APIs del runtime de contenedores expuestas (Docker socket, kubelet)'], verify: ['Escanea imagen: trivy image <imagen>:<tag>', 'Busca contenedores privilegiados: docker inspect $(docker ps -q) | jq .[].HostConfig.Privileged', 'Verifica exposicion del Docker socket: ls -la /var/run/docker.sock'] },
  },
  incident_response: {
    mitre: ['T1485 - Data Destruction', 'T1490 - Inhibit System Recovery', 'T1489 - Service Stop'],
    tools: ['TheHive', 'MISP', 'Velociraptor', 'GRR Rapid Response', 'KAPE'],
    en: { risks: ['Evidence destruction through incorrect response procedures', 'Incomplete containment allowing attacker persistence', 'Excessive response time increasing the blast radius'], verify: ['Isolate system without shutdown: ip link set eth0 down', 'Capture volatile memory: winpmem (Windows) or LiME (Linux)', 'Preserve logs with hash: cp -p /var/log/* /mnt/evidence/'] },
    es: { risks: ['Destruccion de evidencia por procedimientos de respuesta incorrectos', 'Contencion incompleta que permite persistencia del atacante', 'Tiempo de respuesta excesivo que aumenta el impacto'], verify: ['Aisla el sistema sin apagarlo: ip link set eth0 down', 'Captura memoria volatil: winpmem (Windows) o LiME (Linux)', 'Preserva logs con hash: cp -p /var/log/* /mnt/evidence/'] },
  },
  intelligence: {
    mitre: ['T1596 - Search Open Technical Databases', 'T1591 - Gather Victim Org Info', 'T1589 - Gather Victim Identity Information'],
    tools: ['Shodan', 'VirusTotal', 'MISP', 'OpenCTI', 'TheHive'],
    en: { risks: ['Exposed attack surface visible to threat actors', 'IOCs matching known threat actor campaigns', 'Leaked credentials or sensitive data in public sources'], verify: ['Search domain in Shodan: shodan host <ip>', 'Query VirusTotal API for domain/IP reputation', 'Check HaveIBeenPwned: https://haveibeenpwned.com'] },
    es: { risks: ['Superficie de ataque expuesta visible a actores maliciosos', 'IOCs que coinciden con campanas de actores de amenaza conocidos', 'Credenciales filtradas o datos sensibles en fuentes publicas'], verify: ['Busca el dominio en Shodan: shodan host <ip>', 'Consulta la API de VirusTotal para reputacion de dominio/IP', 'Verifica en HaveIBeenPwned: https://haveibeenpwned.com'] },
  },
  monitoring: {
    mitre: ['T1071 - Application Layer Protocol', 'T1046 - Network Service Discovery', 'T1040 - Network Sniffing'],
    tools: ['Zeek', 'Suricata', 'Wireshark', 'Nagios', 'Zabbix', 'Elastic Stack'],
    en: { risks: ['Undetected malicious activity in monitored traffic', 'Log gaps or tampering hiding attacker actions', 'Blind spots in network or endpoint visibility'], verify: ['Monitor active connections: netstat -an | grep ESTABLISHED', 'Check running services: ss -tlnp', 'Review syslog for anomalies: tail -f /var/log/syslog | grep -i error'] },
    es: { risks: ['Actividad maliciosa no detectada en el trafico monitorizado', 'Brechas en logs o manipulacion que ocultan acciones del atacante', 'Puntos ciegos en visibilidad de red o endpoint'], verify: ['Monitorea conexiones activas: netstat -an | grep ESTABLISHED', 'Verifica servicios en escucha: ss -tlnp', 'Revisa syslog en busca de anomalias: tail -f /var/log/syslog | grep -i error'] },
  },
  os_analysis: {
    mitre: ['T1547 - Boot or Logon Autostart', 'T1059 - Command and Scripting Interpreter', 'T1078 - Valid Accounts'],
    tools: ['Sysinternals', 'Lynis', 'chkrootkit', 'auditd', 'osquery'],
    en: { risks: ['Malware persistence via registry, cron or systemd', 'Rootkits hiding malicious processes or files', 'Privilege escalation via SUID binaries or vulnerable services'], verify: ['Check scheduled tasks: crontab -l; schtasks /query /fo LIST', 'Find SUID binaries: find / -perm -4000 -type f 2>/dev/null', 'Check running processes: ps auxf | less'] },
    es: { risks: ['Persistencia de malware via registro, cron o systemd', 'Rootkits que ocultan procesos o archivos maliciosos', 'Escalada de privilegios via binarios SUID o servicios vulnerables'], verify: ['Verifica tareas programadas: crontab -l; schtasks /query /fo LIST', 'Busca binarios SUID: find / -perm -4000 -type f 2>/dev/null', 'Revisa procesos activos: ps auxf | less'] },
  },
  specialized: {
    mitre: ['T1190 - Exploit Public-Facing Application', 'T1059 - Command and Scripting Interpreter'],
    tools: ['Burp Suite', 'OWASP ZAP', 'Metasploit', 'Nikto', 'nmap'],
    en: { risks: ['Domain-specific vulnerabilities exploitable by targeted attackers', 'Insecure configurations unique to the technology stack', 'Compliance gaps specific to the regulated sector'], verify: ['Run vulnerability scan: nikto -h http://target', 'Inspect API endpoints: curl -X OPTIONS http://target/api', 'Check for known CVEs: searchsploit <technology>'] },
    es: { risks: ['Vulnerabilidades especificas del dominio explotables por atacantes dirigidos', 'Configuraciones inseguras unicas del stack tecnologico', 'Brechas de cumplimiento especificas del sector regulado'], verify: ['Ejecuta escaneo de vulnerabilidades: nikto -h http://target', 'Inspecciona endpoints API: curl -X OPTIONS http://target/api', 'Busca CVEs conocidos: searchsploit <tecnologia>'] },
  },
  threats: {
    mitre: ['T1059 - Command and Scripting Interpreter', 'T1071 - Application Layer Protocol', 'T1027 - Obfuscated Files or Information'],
    tools: ['CrowdStrike', 'Carbon Black', 'SentinelOne', 'Elastic Security', 'Suricata'],
    en: { risks: ['Active malware infection or attacker presence in the network', 'Lateral movement enabling access to additional systems', 'Data exfiltration or ransomware deployment in progress'], verify: ['Check active connections: netstat -an | grep -v LISTEN', 'Review recent file changes: find / -newer /tmp/baseline -type f 2>/dev/null', 'Inspect process tree: ps auxf; pstree -p'] },
    es: { risks: ['Infeccion activa de malware o presencia de atacante en la red', 'Movimiento lateral que permite acceso a sistemas adicionales', 'Exfiltracion de datos o despliegue de ransomware en curso'], verify: ['Verifica conexiones activas: netstat -an | grep -v LISTEN', 'Revisa cambios recientes en archivos: find / -newer /tmp/baseline -type f 2>/dev/null', 'Inspecciona arbol de procesos: ps auxf; pstree -p'] },
  },
}

// ── Static detailed docs for key agents ──────────────────────────────────────

const STATIC_DOCS: StaticDoc[] = [
  { agent: 'OSINTInvestigatorAgent', category: 'intelligence', severity: 'HIGH', mitre: ['T1596 - Search Open Technical Databases', 'T1591 - Gather Victim Org Info'], tools: ['Shodan', 'VirusTotal', 'WHOIS', 'DNSDumpster', 'Censys'], content: { es: { label: 'OSINT Investigator', what: 'Reune informacion publica sobre un objetivo usando fuentes abiertas: WHOIS, Shodan, VirusTotal, DNS pasivo y certificados SSL. Genera un perfil completo de exposicion del target.', risks: ['Exposicion de infraestructura en Shodan/Censys', 'Historial DNS que revela subdominios ocultos', 'Registros WHOIS con datos sensibles', 'Certificados SSL que exponen subdominios internos'], verify: ['Ejecuta: whois <dominio> y revisa el campo Registrant Email', 'Busca el dominio en shodan.io y verifica puertos expuestos', 'Usa dnsdumpster.com para ver el historial DNS', 'curl -s "https://crt.sh/?q=%.dominio.com&output=json" | jq .[].name_value'] }, en: { label: 'OSINT Investigator', what: 'Gathers public information about a target using open sources: WHOIS, Shodan, VirusTotal, passive DNS and SSL certificates. Generates a complete exposure profile.', risks: ['Infrastructure exposure on Shodan/Censys', 'DNS history revealing hidden subdomains', 'WHOIS records with sensitive registrant data', 'SSL certificates exposing internal subdomains'], verify: ['Run: whois <domain> and check the Registrant Email field', 'Search domain on shodan.io and check exposed ports', 'Use dnsdumpster.com to see DNS history', 'curl -s "https://crt.sh/?q=%.domain.com&output=json" | jq .[].name_value'] } } },
  { agent: 'DomainIntelligenceAgent', category: 'intelligence', severity: 'HIGH', mitre: ['T1596.001 - DNS/Passive DNS'], tools: ['dig', 'subfinder', 'SecurityTrails', 'RiskIQ'], content: { es: { label: 'Domain Intelligence', what: 'Analiza en profundidad la infraestructura DNS: registros A/MX/TXT/SPF, historial de cambios, subdominios y estado de delegacion.', risks: ['Subdominios huerfanos susceptibles a subdomain takeover', 'Registros SPF/DMARC mal configurados que permiten spoofing', 'Zonas DNS con AXFR habilitado'], verify: ['Ejecuta: dig +short MX dominio.com', 'Verifica SPF: dig TXT dominio.com | grep spf', 'Intenta AXFR: dig axfr @ns1.dominio.com dominio.com', 'Busca subdominios: subfinder -d dominio.com'] }, en: { label: 'Domain Intelligence', what: 'Deep analysis of a domain DNS infrastructure: A/MX/TXT/SPF records, change history, subdomains and delegation status.', risks: ['Orphaned subdomains vulnerable to subdomain takeover', 'Misconfigured SPF/DMARC records allowing email spoofing', 'DNS zones with AXFR zone transfer enabled'], verify: ['Run: dig +short MX domain.com', 'Check SPF: dig TXT domain.com | grep spf', 'Attempt AXFR: dig axfr @ns1.domain.com domain.com', 'Find subdomains: subfinder -d domain.com'] } } },
  { agent: 'PhishingDetectorAgent', category: 'threats', severity: 'HIGH', mitre: ['T1566 - Phishing', 'T1598 - Spearphishing for Info'], tools: ['PhishTank', 'Google Safe Browsing', 'URLScan.io', 'VirusTotal'], content: { es: { label: 'Phishing Detector', what: 'Detecta senales de phishing en URLs y dominios: lookalikes, typosquatting, formularios de captura de credenciales y redirecciones maliciosas.', risks: ['Dominio lookalike disenado para enganar usuarios', 'Pagina de captura de credenciales activa', 'Certificado SSL valido en dominio malicioso'], verify: ['Verifica el dominio en urlscan.io', 'Consulta PhishTank: https://www.phishtank.com', 'Analiza la URL en VirusTotal', 'Revisa la fecha de creacion del dominio: whois | grep Creation Date'] }, en: { label: 'Phishing Detector', what: 'Detects phishing signals in URLs and domains: lookalikes, typosquatting, credential capture forms and malicious redirects.', risks: ['Lookalike domain designed to deceive users', 'Active credential capture page', 'Valid SSL certificate on malicious domain (false legitimacy)'], verify: ['Check domain on urlscan.io', 'Query PhishTank: https://www.phishtank.com', 'Analyze URL in VirusTotal', 'Check domain creation date: whois | grep Creation Date'] } } },
  { agent: 'MalwareDetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1587.001 - Malware', 'T1583.001 - Acquire Infrastructure: Domains'], tools: ['VirusTotal', 'MalwareBazaar', 'Any.run', 'Hybrid-Analysis'], content: { es: { label: 'Malware Detector', what: 'Evalua si un dominio o IP esta asociado a la distribucion de malware. Consulta reputacion en feeds de inteligencia y analiza patrones de comportamiento.', risks: ['Dominio listado como C2 (Command & Control)', 'Distribucion de dropper o ransomware', 'IP en blacklists de multiples feeds'], verify: ['Consulta en MalwareBazaar: https://bazaar.abuse.ch/browse/', 'Verifica la reputacion en AbuseIPDB', 'Escaneo en VirusTotal con 70+ antivirus'] }, en: { label: 'Malware Detector', what: 'Evaluates whether a domain or IP is associated with malware distribution. Queries reputation in intelligence feeds and analyzes behavioral patterns.', risks: ['Domain listed as C2 (Command & Control)', 'Dropper or ransomware distribution', 'IP on blacklists from multiple feeds'], verify: ['Query MalwareBazaar: https://bazaar.abuse.ch/browse/', 'Check reputation on AbuseIPDB: https://www.abuseipdb.com', 'Scan on VirusTotal with 70+ antivirus engines'] } } },
  { agent: 'C2DetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1071 - Application Layer Protocol', 'T1095 - Non-Application Layer Protocol', 'T1102 - Web Service'], tools: ['MISP', 'OpenCTI', 'ThreatFox', 'Shodan'], content: { es: { label: 'C2 / Command & Control', what: 'Detecta infraestructura C2 usada por actores maliciosos para controlar malware. Analiza patrones de trafico, puertos no estandar y IOCs conocidos.', risks: ['Servidor C2 activo (Cobalt Strike, Metasploit, Empire)', 'Comunicacion malware-C2 mediante HTTP/DNS/HTTPS encubierto', 'Uso de servicios legitimos como C2 (GitHub, Pastebin, Discord)'], verify: ['Busca en ThreatFox: https://threatfox.abuse.ch/browse/', 'Verifica JA3 fingerprints: https://ja3er.com/search', 'Consulta MISP feeds de C2 conocidos'] }, en: { label: 'C2 / Command & Control', what: 'Detects C2 infrastructure used by malicious actors to control malware. Analyzes traffic patterns, non-standard ports and known IOCs.', risks: ['Active C2 server (Cobalt Strike, Metasploit, Empire)', 'Malware-C2 communication via covert HTTP/DNS/HTTPS', 'Using legitimate services as C2 (GitHub, Pastebin, Discord)'], verify: ['Search ThreatFox: https://threatfox.abuse.ch/browse/', 'Check JA3 fingerprints: https://ja3er.com/search', 'Query MISP feeds of known C2s'] } } },
  { agent: 'BruteForceDetectorAgent', category: 'threats', severity: 'HIGH', mitre: ['T1110 - Brute Force', 'T1110.001 - Password Guessing', 'T1110.003 - Password Spraying'], tools: ['fail2ban', 'Hydra (test)', 'CrowdStrike Falcon'], content: { es: { label: 'Brute Force Detector', what: 'Detecta ataques de fuerza bruta contra servicios expuestos: SSH, RDP, FTP, paneles web y APIs.', risks: ['Acceso no autorizado por credenciales debiles', 'Account lockout masivo (DoS)', 'Password spraying con credenciales comunes'], verify: ['Revisa logs SSH: grep "Failed password" /var/log/auth.log | tail -50', 'Cuenta intentos fallidos por IP en /var/log/auth.log', 'Verifica si fail2ban esta activo: fail2ban-client status sshd'] }, en: { label: 'Brute Force Detector', what: 'Detects brute force attacks against exposed services: SSH, RDP, FTP, web panels and APIs.', risks: ['Unauthorized access through weak credentials', 'Mass account lockout (DoS)', 'Password spraying with common credentials'], verify: ['Check SSH logs: grep "Failed password" /var/log/auth.log | tail -50', 'Count failed attempts per IP in /var/log/auth.log', 'Check if fail2ban is active: fail2ban-client status sshd'] } } },
  { agent: 'RansomwareDetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1486 - Data Encrypted for Impact', 'T1490 - Inhibit System Recovery'], tools: ['Cuckoo Sandbox', 'Velociraptor', 'KAPE', 'Volatility'], content: { es: { label: 'Ransomware Detector', what: 'Detecta actividad de ransomware: cifrado masivo de archivos, eliminacion de shadow copies y comunicacion con servidores de pago.', risks: ['Cifrado masivo de archivos del sistema de archivos', 'Eliminacion de backups y shadow copies', 'Propagacion lateral a otros hosts'], verify: ['Verifica shadow copies: vssadmin list shadows (Windows)', 'Busca archivos cifrados: find / -name "*.encrypted" 2>/dev/null', 'Monitorea actividad I/O: iotop -oa'] }, en: { label: 'Ransomware Detector', what: 'Detects ransomware activity: mass file encryption, shadow copy deletion and payment server communication.', risks: ['Mass encryption of filesystem files', 'Deletion of backups and shadow copies', 'Lateral propagation to other network hosts'], verify: ['Check shadow copies: vssadmin list shadows (Windows)', 'Find encrypted files: find / -name "*.encrypted" 2>/dev/null', 'Monitor I/O activity: iotop -oa'] } } },
  { agent: 'DataExfiltrationDetectorAgent', category: 'threats', severity: 'HIGH', mitre: ['T1048 - Exfiltration Over Alternative Protocol', 'T1041 - Exfiltration Over C2 Channel'], tools: ['Wireshark', 'Zeek', 'Suricata'], content: { es: { label: 'Data Exfiltration', what: 'Detecta transferencia no autorizada de datos hacia el exterior via canales encubiertos (DNS tunneling, HTTPS) y acceso inusual a repositorios de datos.', risks: ['Exfiltracion masiva de base de datos', 'DNS tunneling para transferir datos en consultas DNS', 'Upload a servicios cloud no autorizados'], verify: ['Analiza trafico DNS con Zeek buscando strings base64 largos', 'Monitorea transferencias grandes: tcpdump -i eth0 -w capture.pcap port 443', 'Revisa logs de proxy web para uploads a servicios cloud'] }, en: { label: 'Data Exfiltration', what: 'Detects unauthorized data transfer to external destinations via covert channels (DNS tunneling, HTTPS) and unusual data repository access.', risks: ['Mass database exfiltration (dump)', 'DNS tunneling to transfer data in DNS queries', 'Upload to unauthorized cloud services'], verify: ['Analyze DNS traffic with Zeek looking for long base64 strings', 'Monitor large transfers: tcpdump -i eth0 -w capture.pcap port 443', 'Review web proxy logs for uploads to cloud services'] } } },
  { agent: 'AWSAnalyzerAgent', category: 'cloud', severity: 'HIGH', mitre: ['T1078.004 - Cloud Accounts', 'T1530 - Data from Cloud Storage'], tools: ['AWS CLI', 'ScoutSuite', 'Prowler', 'CloudMapper'], content: { es: { label: 'AWS Analyzer', what: 'Audita la postura de seguridad de una cuenta AWS: IAM, S3, EC2, VPC, CloudTrail y GuardDuty.', risks: ['Buckets S3 publicos con datos sensibles', 'Roles IAM con permisos wildcard', 'Security groups con puertos abiertos a 0.0.0.0/0'], verify: ['Audita con Prowler: prowler aws --region us-east-1', 'Busca buckets publicos: aws s3api list-buckets', 'Verifica CloudTrail: aws cloudtrail get-trail-status --name <trail>'] }, en: { label: 'AWS Analyzer', what: 'Audits the security posture of an AWS account: IAM, S3, EC2, VPC, CloudTrail and GuardDuty.', risks: ['Public S3 buckets with sensitive data', 'IAM roles with wildcard permissions', 'Security groups with ports open to 0.0.0.0/0'], verify: ['Audit with Prowler: prowler aws --region us-east-1', 'Find public buckets: aws s3api list-buckets', 'Verify CloudTrail: aws cloudtrail get-trail-status --name <trail>'] } } },
  { agent: 'KubernetesAnalyzerAgent', category: 'containers', severity: 'HIGH', mitre: ['T1610 - Deploy Container', 'T1613 - Container and Resource Discovery'], tools: ['kube-bench', 'Trivy', 'Falco', 'kubectl'], content: { es: { label: 'Kubernetes Analyzer', what: 'Evalua la postura de seguridad de un cluster Kubernetes: RBAC, network policies, pod security contexts y secrets expuestos.', risks: ['Pods corriendo como root', 'RBAC con permisos cluster-admin excesivos', 'Secrets almacenados en texto plano'], verify: ['Ejecuta kube-bench: kubectl apply -f kube-bench-job.yaml', 'Escanea imagenes: trivy image nombre-imagen:tag', 'Lista cluster-admin bindings: kubectl get clusterrolebindings'] }, en: { label: 'Kubernetes Analyzer', what: 'Evaluates the security posture of a Kubernetes cluster: RBAC, network policies, pod security contexts and exposed secrets.', risks: ['Pods running as root', 'RBAC with excessive cluster-admin permissions', 'Secrets stored in plain text in ConfigMaps'], verify: ['Run kube-bench: kubectl apply -f kube-bench-job.yaml', 'Scan images: trivy image image-name:tag', 'List cluster-admin bindings: kubectl get clusterrolebindings'] } } },
  { agent: 'WindowsAnalyzerAgent', category: 'os_analysis', severity: 'HIGH', mitre: ['T1547 - Boot or Logon Autostart', 'T1059.001 - PowerShell', 'T1003 - OS Credential Dumping'], tools: ['Sysinternals Suite', 'Volatility', 'KAPE', 'Autoruns'], content: { es: { label: 'Windows Analyzer', what: 'Analisis de seguridad de sistemas Windows: event logs, registro, procesos, servicios, tareas programadas y persistencia.', risks: ['Malware con persistencia en registro (Run keys)', 'Pass-the-Hash / Kerberoasting', 'PowerShell ofuscado descargando payload en memoria'], verify: ['Revisa Autoruns.exe para ver todos los puntos de persistencia', 'Busca comandos sospechosos en Event ID 4688', 'Verifica integridad del sistema: sfc /scannow'] }, en: { label: 'Windows Analyzer', what: 'Security analysis of Windows systems: event logs, registry, processes, services, scheduled tasks and persistence.', risks: ['Malware with registry persistence (Run keys)', 'Pass-the-Hash / Kerberoasting', 'Obfuscated PowerShell or in-memory payload download'], verify: ['Check Autoruns.exe to see all persistence points', 'Look for suspicious commands in Event ID 4688 (Process Creation)', 'Verify system file integrity: sfc /scannow'] } } },
  { agent: 'LinuxAnalyzerAgent', category: 'os_analysis', severity: 'HIGH', mitre: ['T1053.003 - Cron', 'T1543.002 - Systemd Service', 'T1078.003 - Local Accounts'], tools: ['Lynis', 'chkrootkit', 'rkhunter', 'auditd'], content: { es: { label: 'Linux Analyzer', what: 'Analisis de seguridad de sistemas Linux: usuarios, permisos SUID, cron jobs, servicios activos, modulos del kernel y configuracion SSH.', risks: ['Binarios SUID no autorizados para escalada de privilegios', 'SSH con root login y autenticacion por contrasena habilitados', 'Modulos del kernel maliciosos (rootkits)'], verify: ['Audita con Lynis: lynis audit system', 'Busca SUID inusuales: find / -perm -4000 -type f 2>/dev/null', 'Verifica config SSH: grep -E "PermitRootLogin|PasswordAuth" /etc/ssh/sshd_config'] }, en: { label: 'Linux Analyzer', what: 'Security analysis of Linux systems: users, SUID permissions, cron jobs, active services, kernel modules and SSH configuration.', risks: ['Unauthorized SUID binaries for privilege escalation', 'SSH with root login and password authentication enabled', 'Malicious kernel modules (rootkits)'], verify: ['Audit with Lynis: lynis audit system', 'Find unusual SUID: find / -perm -4000 -type f 2>/dev/null', 'Verify SSH config: grep -E "PermitRootLogin|PasswordAuth" /etc/ssh/sshd_config'] } } },
  { agent: 'ComplianceAuditorAgent', category: 'compliance', severity: 'MEDIUM', mitre: [], tools: ['OpenSCAP', 'Lynis', 'ScoutSuite', 'Prowler'], content: { es: { label: 'Compliance Auditor', what: 'Verifica el cumplimiento de estandares: ISO 27001, SOC 2, PCI-DSS, HIPAA y GDPR.', risks: ['Datos personales sin cifrar (GDPR)', 'Gestion de parches deficiente', 'Logs de auditoria incompletos'], verify: ['Ejecuta OpenSCAP: oscap oval eval --report report.html oval.xml', 'Verifica retencion de logs: find /var/log -mtime +90 | wc -l', 'Revisa politica de contrasenas: chage -l usuario'] }, en: { label: 'Compliance Auditor', what: 'Verifies compliance with security standards: ISO 27001, SOC 2, PCI-DSS, HIPAA and GDPR.', risks: ['Unencrypted personal data (GDPR)', 'Poor patch management', 'Incomplete audit logs'], verify: ['Run OpenSCAP: oscap oval eval --report report.html oval.xml', 'Check log retention: find /var/log -mtime +90 | wc -l', 'Review password policy: chage -l user'] } } },
  { agent: 'IncidentResponderAgent', category: 'incident_response', severity: 'CRITICAL', mitre: ['T1489 - Service Stop', 'T1485 - Data Destruction'], tools: ['TheHive', 'MISP', 'Velociraptor', 'GRR Rapid Response'], content: { es: { label: 'Incident Responder', what: 'Coordina la respuesta a incidentes: triaje, contencion, erradicacion y recuperacion.', risks: ['Incidente no contenido que escala', 'Destruccion de evidencia por respuesta incorrecta', 'Tiempo de respuesta excesivo'], verify: ['Aisla el sistema: ip link set eth0 down (sin apagar)', 'Captura memoria RAM: winpmem/LiME', 'Preserva logs: cp -p /var/log/* /mnt/evidence/'] }, en: { label: 'Incident Responder', what: 'Coordinates security incident response: triage, containment, eradication and recovery.', risks: ['Uncontained incident escalating to full system compromise', 'Forensic evidence destruction through incorrect response', 'Excessive response time increasing impact'], verify: ['Isolate the system: ip link set eth0 down (without shutting down)', 'Capture RAM memory: winpmem (Windows) / LiME (Linux)', 'Preserve logs: cp -p /var/log/* /mnt/evidence/'] } } },
  { agent: 'SQLInjectionDetectorAgent', category: 'specialized', severity: 'CRITICAL', mitre: ['T1190 - Exploit Public-Facing Application', 'T1059 - Command and Scripting Interpreter'], tools: ['sqlmap', 'Burp Suite', 'OWASP ZAP', 'Nikto'], content: { es: { label: 'SQL Injection Detector', what: 'Detecta vectores de inyeccion SQL en aplicaciones web: inyecciones clasicas, ciegas (blind), basadas en tiempo y fuera de banda.', risks: ['Extraccion completa de la base de datos', 'Bypass de autenticacion mediante OR 1=1', 'Ejecucion de comandos del SO via xp_cmdshell (MSSQL)'], verify: ['Prueba con sqlmap: sqlmap -u "http://target.com/page?id=1" --dbs', 'Test manual: agrega una comilla simple al parametro', 'Usa Burp Suite para interceptar y modificar requests'] }, en: { label: 'SQL Injection Detector', what: 'Detects SQL injection vectors in web applications: classic, blind, time-based and out-of-band injections.', risks: ['Complete database extraction', 'Authentication bypass using OR 1=1', 'OS command execution via xp_cmdshell (MSSQL)'], verify: ['Test with sqlmap: sqlmap -u "http://target.com/page?id=1" --dbs', 'Manual test: add a single quote to the parameter and observe the error', 'Use Burp Suite to intercept and modify requests'] } } },
  { agent: 'APTDetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1566 - Phishing', 'T1078 - Valid Accounts', 'T1021 - Remote Services', 'T1053 - Scheduled Task/Job'], tools: ['MISP', 'OpenCTI', 'CrowdStrike', 'Darktrace'], content: { es: { label: 'APT Detector', what: 'Detecta campanas de amenazas persistentes avanzadas (APT). Correlaciona TTPs de MITRE ATT&CK, IOCs de actores conocidos y comportamiento sigiloso de larga duracion.', risks: ['Presencia silenciosa de un actor avanzado durante meses', 'Spear-phishing dirigido a empleados clave', 'Movimiento lateral encubierto usando herramientas legitimas'], verify: ['Correlaciona logs con feeds de inteligencia de amenazas en MISP', 'Busca conexiones a IPs/dominios de APTs conocidos en logs de red', 'Analiza eventos de autenticacion fuera de horario: Event ID 4624'] }, en: { label: 'APT Detector', what: 'Detects Advanced Persistent Threat (APT) campaigns. Correlates MITRE ATT&CK TTPs, known actor IOCs and long-duration stealthy behavior.', risks: ['Silent presence of an advanced actor for months', 'Spear-phishing targeting key employees', 'Covert lateral movement using legitimate tools (living-off-the-land)'], verify: ['Correlate logs with threat intelligence feeds in MISP', 'Search for connections to known APT IPs/domains in network logs', 'Analyze authentication events outside business hours: Event ID 4624'] } } },
  { agent: 'LateralMovementDetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1021 - Remote Services', 'T1075 - Pass the Hash', 'T1076 - Remote Desktop Protocol'], tools: ['Zeek', 'Suricata', 'Windows Event Log', 'Sysmon'], content: { es: { label: 'Lateral Movement', what: 'Detecta movimiento lateral en la red: uso de credenciales robadas para acceder a sistemas adyacentes via SMB, WinRM, RDP, SSH o PsExec.', risks: ['Compromiso en cadena de multiples sistemas desde una sola brecha', 'Pass-the-Hash usando hashes NTLM robados', 'Uso de herramientas nativas (PsExec, WMI) que evaden deteccion'], verify: ['Busca conexiones SMB anomalas: Event ID 4648 (logon con credenciales explicitas)', 'Monitorea WMI activity: Event ID 4104 en PowerShell logs', 'Analiza conexiones RDP inusuales: Event ID 4624 con Logon Type 10'] }, en: { label: 'Lateral Movement', what: 'Detects lateral movement in the network: use of stolen credentials to access adjacent systems via SMB, WinRM, RDP, SSH or PsExec.', risks: ['Chain compromise of multiple systems from a single initial breach', 'Pass-the-Hash using stolen NTLM hashes', 'Use of native tools (PsExec, WMI) evading detection'], verify: ['Look for anomalous SMB connections: Event ID 4648 (logon with explicit credentials)', 'Monitor WMI activity: Event ID 4104 in PowerShell logs', 'Analyze unusual RDP connections: Event ID 4624 with Logon Type 10'] } } },
  { agent: 'PrivilegeEscalationDetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1068 - Exploitation for Privilege Escalation', 'T1055 - Process Injection', 'T1134 - Access Token Manipulation'], tools: ['PEASS-ng', 'BloodHound', 'LinPEAS', 'WinPEAS'], content: { es: { label: 'Privilege Escalation', what: 'Detecta intentos de escalada de privilegios: explotacion de vulnerabilidades del kernel, abuso de tokens, SUID en Linux y UAC bypass en Windows.', risks: ['Acceso root/SYSTEM mediante explotacion de kernel', 'Abuso de servicios mal configurados para ejecutar codigo con privilegios', 'DLL hijacking en aplicaciones con privilegios elevados'], verify: ['Ejecuta LinPEAS en Linux: ./linpeas.sh | tee /tmp/linpeas_output.txt', 'Busca servicios con permisos debiles: sc qc <service> (Windows)', 'Analiza tokens de acceso: Event ID 4672 (Special Logon) en Windows'] }, en: { label: 'Privilege Escalation', what: 'Detects privilege escalation attempts: kernel vulnerability exploitation, token abuse, SUID on Linux and UAC bypass on Windows.', risks: ['Root/SYSTEM access via kernel exploitation', 'Abuse of misconfigured services to execute code with privileges', 'DLL hijacking in applications with elevated privileges'], verify: ['Run LinPEAS on Linux: ./linpeas.sh | tee /tmp/linpeas_output.txt', 'Find services with weak permissions: sc qc <service> (Windows)', 'Analyze access tokens: Event ID 4672 (Special Logon) on Windows'] } } },
  { agent: 'XSSDetectorAgent', category: 'specialized', severity: 'HIGH', mitre: ['T1059.007 - JavaScript', 'T1185 - Browser Session Hijacking'], tools: ['Burp Suite', 'OWASP ZAP', 'XSStrike', 'Dalfox'], content: { es: { label: 'XSS Detector', what: 'Detecta vectores de Cross-Site Scripting (XSS): reflected, stored y DOM-based. Evalua el impacto en robo de sesiones y defacement.', risks: ['Robo de cookies de sesion (session hijacking)', 'Defacement de paginas web', 'Phishing mediante inyeccion de formularios falsos'], verify: ['Prueba: <script>alert(1)</script> en campos de entrada', 'Usa Dalfox: dalfox url "http://target.com/page?param=FUZZ"', 'Inspecciona el codigo fuente buscando inputs no sanitizados'] }, en: { label: 'XSS Detector', what: 'Detects Cross-Site Scripting (XSS) vectors: reflected, stored and DOM-based. Evaluates impact on session theft and defacement.', risks: ['Session cookie theft (session hijacking)', 'Web page defacement', 'Phishing via injection of fake forms into the page'], verify: ['Test: <script>alert(1)</script> in input fields', 'Use Dalfox: dalfox url "http://target.com/page?param=FUZZ"', 'Inspect source code looking for unsanitized inputs'] } } },
  { agent: 'RootkitDetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1014 - Rootkit', 'T1547.006 - Kernel Modules and Extensions'], tools: ['chkrootkit', 'rkhunter', 'OSSEC', 'Volatility'], content: { es: { label: 'Rootkit Detector', what: 'Detecta rootkits: modulos del kernel maliciosos, hooking de syscalls, procesos ocultos y backdoors persistentes.', risks: ['Proceso malicioso completamente oculto del sistema operativo', 'Kernel comprometido con modulo que intercepta syscalls', 'Backdoor persistente que sobrevive reinicios'], verify: ['Ejecuta chkrootkit: chkrootkit 2>&1 | grep -i INFECTED', 'Ejecuta rkhunter: rkhunter --check --skip-keypress', 'Compara syscall table: cat /proc/kallsyms | grep sys_call_table'] }, en: { label: 'Rootkit Detector', what: 'Detects rootkits: malicious kernel modules, syscall hooking, hidden processes and persistent backdoors.', risks: ['Malicious process completely hidden from the operating system', 'Compromised kernel with module intercepting syscalls', 'Persistent backdoor surviving reboots'], verify: ['Run chkrootkit: chkrootkit 2>&1 | grep -i INFECTED', 'Run rkhunter: rkhunter --check --skip-keypress', 'Compare syscall table for hooks: cat /proc/kallsyms | grep sys_call_table'] } } },
  { agent: 'DDoSDetectorAgent', category: 'threats', severity: 'HIGH', mitre: ['T1498 - Network Denial of Service', 'T1499 - Endpoint Denial of Service'], tools: ['Cloudflare', 'Arbor Networks', 'tcpdump', 'Wireshark'], content: { es: { label: 'DDoS Detector', what: 'Detecta ataques de Denegacion de Servicio Distribuido: volumetricos (UDP/SYN flood), de protocolo y de aplicacion (HTTP flood, Slowloris).', risks: ['Saturacion del ancho de banda disponible', 'Agotamiento de recursos del servidor (CPU, conexiones)', 'Interrupcion de servicio para usuarios legitimos'], verify: ['Monitorea trafico por IP origen: tcpdump -i eth0 -n port 80', 'Verifica SYN flood: netstat -s | grep "SYNs to LISTEN"', 'Analiza trafico con Wireshark filtrando por ip.addr == <source>'] }, en: { label: 'DDoS Detector', what: 'Detects Distributed Denial of Service attacks: volumetric (UDP/SYN flood), protocol-based and application-layer (HTTP flood, Slowloris).', risks: ['Saturation of available bandwidth', 'Server resource exhaustion (CPU, connections)', 'Service interruption for legitimate users'], verify: ['Monitor traffic by source IP: tcpdump -i eth0 -n port 80', 'Check SYN flood: netstat -s | grep "SYNs to LISTEN"', 'Analyze traffic in Wireshark filtering by ip.addr == <source>'] } } },
  { agent: 'InsiderThreatDetectorAgent', category: 'threats', severity: 'HIGH', mitre: ['T1078 - Valid Accounts', 'T1052 - Exfiltration Over Physical Medium', 'T1074 - Data Staged'], tools: ['Splunk UBA', 'Microsoft Sentinel', 'Varonis', 'Dtex Systems'], content: { es: { label: 'Insider Threat', what: 'Detecta actividad maliciosa o negligente de usuarios internos: descarga masiva de datos, acceso a recursos fuera del rol y comportamiento anomalo.', risks: ['Empleado con acceso privilegiado exfiltrando datos sensibles', 'Cuenta comprometida de usuario interno usada por atacante externo', 'Sabotaje de sistemas criticos por empleado descontento'], verify: ['Analiza accesos inusuales con UEBA: busca desvios del baseline por usuario', 'Monitorea descargas masivas de archivos sensibles', 'Revisa actividad fuera de horario: Event ID 4624 en horas no laborales'] }, en: { label: 'Insider Threat', what: 'Detects malicious or negligent activity from internal users: mass data downloads, access to out-of-role resources and anomalous behavior.', risks: ['Privileged employee exfiltrating sensitive data', 'Compromised internal user account used by external attacker', 'Critical system sabotage by disgruntled employee'], verify: ['Analyze unusual access with UEBA: look for deviations from per-user baseline', 'Monitor mass downloads of sensitive files', 'Review out-of-hours activity: Event ID 4624 during non-business hours'] } } },
  { agent: 'SIEMMonitorAgent', category: 'monitoring', severity: 'CRITICAL', mitre: ['T1070 - Indicator Removal on Host', 'T1562 - Impair Defenses'], tools: ['Splunk', 'IBM QRadar', 'Microsoft Sentinel', 'Elastic SIEM', 'Wazuh'], content: { es: { label: 'SIEM Monitor', what: 'Monitoreo central de eventos de seguridad con correlacion avanzada. Agrega logs de multiples fuentes, aplica reglas de deteccion y genera alertas priorizadas.', risks: ['Volumen de eventos que supera la capacidad de analisis', 'Reglas de correlacion desactualizadas', 'Atacante que borra logs para eliminar evidencia'], verify: ['Verifica que todos los dispositivos esten enviando logs', 'Comprueba integridad de logs: busca brechas temporales en el feed', 'Verifica que las reglas criticas esten activas'] }, en: { label: 'SIEM Monitor', what: 'Central security event monitoring with advanced correlation. Aggregates logs from multiple sources, applies detection rules and generates prioritized alerts.', risks: ['Event volume exceeding analysis capacity', 'Outdated correlation rules missing new threats', 'Attacker deleting logs to remove evidence'], verify: ['Verify all devices are sending logs: check "last seen" for each source', 'Check log integrity: look for time gaps in the feed', 'Verify that critical rules are active and generating alerts'] } } },
  { agent: 'FileIntegrityMonitorAgent', category: 'monitoring', severity: 'HIGH', mitre: ['T1565 - Data Manipulation', 'T1070.006 - Timestomp'], tools: ['OSSEC', 'Wazuh', 'Tripwire', 'AIDE', 'auditd'], content: { es: { label: 'File Integrity Monitor', what: 'Monitorea la integridad de archivos criticos del sistema: binarios, configuraciones, librerias. Detecta modificaciones no autorizadas comparando hashes.', risks: ['Binario del sistema reemplazado por version troyanizada', 'Archivo de configuracion modificado para dar acceso persistente', 'Timestomping para ocultar cuando ocurrio la modificacion'], verify: ['Inicializa AIDE: aide --init && mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db', 'Verifica integridad: aide --check 2>&1 | grep -v "^$"', 'Compara hashes: sha256sum /usr/bin/ssh /bin/ls /sbin/sshd contra valores conocidos'] }, en: { label: 'File Integrity Monitor', what: 'Monitors the integrity of critical system files: binaries, configurations, libraries. Detects unauthorized modifications by comparing hashes.', risks: ['System binary replaced by trojaned version', 'Configuration file modified to provide persistent access', 'Timestomping to hide when modification occurred'], verify: ['Initialize AIDE: aide --init && mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db', 'Verify integrity: aide --check 2>&1 | grep -v "^$"', 'Compare hashes: sha256sum /usr/bin/ssh /bin/ls /sbin/sshd against known values'] } } },
  { agent: 'CVEAnalyzerAgent', category: 'intelligence', severity: 'HIGH', mitre: ['T1203 - Exploitation for Client Execution', 'T1190 - Exploit Public-Facing Application'], tools: ['Nessus', 'OpenVAS', 'Nuclei', 'Metasploit', 'NVD API'], content: { es: { label: 'CVE Analyzer', what: 'Analiza vulnerabilidades conocidas (CVEs) en el software detectado. Correlaciona versiones con NVD/CVE database y evalua criticidad CVSS y disponibilidad de exploits.', risks: ['Software con CVE critico y exploit publico disponible', 'Sistema sin parche durante ventana de explotacion activa', 'Vulnerabilidad en componente de terceros de la cadena de suministro'], verify: ['Escanea con Nuclei: nuclei -u http://target -t cves/', 'Verifica versiones: nmap -sV --script=banner <ip>', 'Consulta NVD: https://nvd.nist.gov/vuln/search'] }, en: { label: 'CVE Analyzer', what: 'Analyzes known vulnerabilities (CVEs) in detected software. Correlates versions with NVD/CVE database and evaluates CVSS criticality and exploit availability.', risks: ['Software with critical CVE and available public exploit', 'Unpatched system during active exploitation window', 'Vulnerability in third-party supply chain component'], verify: ['Scan with Nuclei: nuclei -u http://target -t cves/', 'Verify exposed versions: nmap -sV --script=banner <ip>', 'Query NVD: https://nvd.nist.gov/vuln/search'] } } },
  { agent: 'IAMAnalyzerAgent', category: 'cloud', severity: 'CRITICAL', mitre: ['T1078.004 - Cloud Accounts', 'T1098 - Account Manipulation', 'T1136.003 - Cloud Account'], tools: ['AWS IAM Access Analyzer', 'BloodHound', 'PMapper', 'Prowler'], content: { es: { label: 'IAM Analyzer', what: 'Analiza politicas IAM en entornos cloud. Detecta permisos excesivos, roles sin usar, claves antiguas y rutas de escalada de privilegios.', risks: ['Roles con AdministratorAccess o permisos wildcard', 'Claves de acceso antiguas (>90 dias) sin rotacion', 'Rutas de escalada de privilegios mediante AssumeRole encadenado'], verify: ['Analiza rutas de escalada con PMapper: pmapper --profile default graph create', 'Lista claves viejas: aws iam list-access-keys --user-name <user>', 'Activa IAM Access Analyzer: aws accessanalyzer create-analyzer --analyzer-name analyzer --type ACCOUNT'] }, en: { label: 'IAM Analyzer', what: 'Analyzes IAM policies in cloud environments. Detects excessive permissions, unused roles, old keys and privilege escalation paths.', risks: ['Roles with AdministratorAccess or wildcard permissions', 'Old access keys (>90 days) without rotation', 'Privilege escalation paths via chained AssumeRole'], verify: ['Analyze escalation paths with PMapper: pmapper --profile default graph create', 'List old keys: aws iam list-access-keys --user-name <user>', 'Enable IAM Access Analyzer: aws accessanalyzer create-analyzer --analyzer-name analyzer --type ACCOUNT'] } } },
  { agent: 'NetworkTrafficMonitorAgent', category: 'monitoring', severity: 'HIGH', mitre: ['T1040 - Network Sniffing', 'T1046 - Network Service Discovery'], tools: ['Zeek', 'Suricata', 'Wireshark', 'ntopng', 'Argus'], content: { es: { label: 'Network Traffic Monitor', what: 'Monitorea el trafico de red en tiempo real buscando anomalias, conexiones sospechosas, escaneos de puertos y comunicaciones a destinos maliciosos conocidos.', risks: ['Comunicacion con IPs de C2 o botnet listadas en feeds de inteligencia', 'Escaneo de puertos interno (reconocimiento de red)', 'Trafico cifrado inusual en puertos no estandar'], verify: ['Captura trafico: tcpdump -i any -w /tmp/capture.pcap -c 10000', 'Analiza con Zeek: zeek -r capture.pcap', 'Busca conexiones a IPs maliciosas: grep -f malicious-ips.txt /var/log/zeek/conn.log'] }, en: { label: 'Network Traffic Monitor', what: 'Monitors network traffic in real time looking for anomalies, suspicious connections, port scans and communications to known malicious destinations.', risks: ['Communication with C2 or botnet IPs listed in intelligence feeds', 'Internal port scanning (network reconnaissance)', 'Unusual encrypted traffic on non-standard ports'], verify: ['Capture traffic: tcpdump -i any -w /tmp/capture.pcap -c 10000', 'Analyze with Zeek: zeek -r capture.pcap', 'Search for connections to malicious IPs: grep -f malicious-ips.txt /var/log/zeek/conn.log'] } } },
  { agent: 'ThreatHunterAgent', category: 'analytics', severity: 'CRITICAL', mitre: ['T1078 - Valid Accounts', 'T1027 - Obfuscated Files', 'T1036 - Masquerading'], tools: ['Elastic SIEM', 'Splunk', 'CrowdStrike Overwatch', 'Velociraptor'], content: { es: { label: 'Threat Hunter', what: 'Realiza caceria proactiva de amenazas buscando TTPs de atacantes que evaden deteccion automatizada. Analiza logs historicos, comportamiento de usuarios y actividad de procesos.', risks: ['Actor avanzado persistente no detectado por herramientas automaticas', 'Tecnicas living-off-the-land que evaden antivirus', 'Movimiento lateral silencioso usando credenciales validas'], verify: ['Busca procesos que llaman a powershell.exe desde Office', 'SIEM query: process.parent.name:"winword.exe" AND process.name:"powershell.exe"', 'Busca strings base64 en argumentos de proceso como indicador de evasion'] }, en: { label: 'Threat Hunter', what: 'Performs proactive threat hunting looking for attacker TTPs that evade automated detection. Analyzes historical logs, user behavior and process activity.', risks: ['Advanced persistent actor undetected by automated tools', 'Living-off-the-land techniques evading antivirus', 'Silent lateral movement using valid credentials'], verify: ['Look for processes calling powershell.exe from Office', 'SIEM query: process.parent.name:"winword.exe" AND process.name:"powershell.exe"', 'Search for base64-encoded strings in process arguments as evasion indicator'] } } },
  { agent: 'UEBAAnalyzerAgent', category: 'analytics', severity: 'HIGH', mitre: ['T1078 - Valid Accounts', 'T1133 - External Remote Services'], tools: ['Microsoft Sentinel UEBA', 'Splunk UBA', 'Exabeam', 'Varonis'], content: { es: { label: 'UEBA Analyzer', what: 'User and Entity Behavior Analytics: crea baselines de comportamiento por usuario. Detecta desviaciones estadisticas que indican compromiso de cuenta o amenaza interna.', risks: ['Cuenta comprometida con actividad fuera del patron normal', 'Empleado con acceso inusual a datos fuera de su rol', 'Acceso desde ubicacion geografica o dispositivo nunca antes visto'], verify: ['Revisa el risk score por usuario en tu plataforma UEBA', 'Analiza logins desde nuevas geolocalizaciones: Event ID 4624 con IP inusual', 'Busca descargas masivas de archivos en SharePoint/OneDrive'] }, en: { label: 'UEBA Analyzer', what: 'User and Entity Behavior Analytics: creates behavioral baselines per user. Detects statistical deviations indicating account compromise or insider threat.', risks: ['Compromised user account with activity outside normal pattern', 'Employee with unusual access to data outside their role', 'Access from never-before-seen geographic location or device'], verify: ['Review per-user risk score in your UEBA platform', 'Analyze logins from new geolocations: Event ID 4624 with unusual public IP', 'Search for mass file downloads in SharePoint/OneDrive'] } } },
  { agent: 'IoTSecurityAgent', category: 'specialized', severity: 'HIGH', mitre: ['T1200 - Hardware Additions', 'T1571 - Non-Standard Port'], tools: ['Shodan', 'nmap', 'Firmware Analysis Toolkit', 'binwalk'], content: { es: { label: 'IoT Security', what: 'Analiza la seguridad de dispositivos IoT: camaras, routers, PLCs, sensores. Detecta firmware vulnerable, credenciales por defecto y servicios expuestos.', risks: ['Credenciales por defecto sin cambiar (admin/admin)', 'Firmware con vulnerabilidades criticas conocidas', 'Servicio Telnet o SSH expuesto con autenticacion debil'], verify: ['Escanea IoT en la red: nmap -sV --script=banner 192.168.0.0/24', 'Busca dispositivos en Shodan: shodan search "Hikvision"', 'Analiza firmware: binwalk -e firmware.bin'] }, en: { label: 'IoT Security', what: 'Analyzes the security of IoT devices: cameras, routers, PLCs, sensors. Detects vulnerable firmware, default credentials and exposed services.', risks: ['Default credentials unchanged (admin/admin)', 'Firmware with known critical vulnerabilities (CVEs)', 'Exposed Telnet or SSH service with weak authentication'], verify: ['Scan IoT devices: nmap -sV --script=banner 192.168.0.0/24', 'Search devices in Shodan: shodan search "Hikvision"', 'Analyze firmware: binwalk -e firmware.bin'] } } },
  { agent: 'CodeSecurityAgent', category: 'specialized', severity: 'HIGH', mitre: ['T1195 - Supply Chain Compromise', 'T1059 - Command and Scripting Interpreter'], tools: ['Semgrep', 'Snyk', 'SonarQube', 'Bandit', 'OWASP Dependency Check'], content: { es: { label: 'Code Security', what: 'Analiza el codigo fuente y dependencias en busca de vulnerabilidades: inyecciones, secretos hardcodeados y dependencias con CVEs conocidos.', risks: ['Credenciales o claves API hardcodeadas en el codigo fuente', 'Dependencia de terceros con CVE critico en produccion', 'Inyeccion SQL/NoSQL por falta de sanitizacion de entrada'], verify: ['Escanea con Semgrep: semgrep --config=p/security-audit /', 'Busca secretos: git log -p | grep -E "password|secret|api_key"', 'Analiza dependencias: snyk test --file=package.json'] }, en: { label: 'Code Security', what: 'Analyzes source code and dependencies for vulnerabilities: injections, hardcoded secrets and dependencies with known CVEs.', risks: ['Credentials or API keys hardcoded in source code', 'Third-party dependency with critical CVE in production', 'SQL/NoSQL injection due to lack of input sanitization'], verify: ['Scan with Semgrep: semgrep --config=p/security-audit /', 'Search for secrets: git log -p | grep -E "password|secret|api_key"', 'Analyze dependencies: snyk test --file=package.json'] } } },
  { agent: 'ICSAnalyzerAgent', category: 'specialized', severity: 'CRITICAL', mitre: ['T0800 - Activate Firmware Update Mode', 'T0843 - Program Download', 'T0855 - Unauthorized Command Message'], tools: ['Claroty', 'Dragos', 'Nessus for OT', 'Shodan'], content: { es: { label: 'ICS/SCADA Analyzer', what: 'Analiza la seguridad de sistemas de control industrial (ICS/SCADA/OT): PLCs, HMIs, historidores y redes industriales.', risks: ['PLC accesible desde Internet sin autenticacion', 'Protocolo industrial inseguro expuesto (Modbus, DNP3, BACnet)', 'Acceso no autorizado al sistema de control'], verify: ['Escanea sistemas OT con Nessus con plugins ICS/SCADA', 'Busca PLCs en Shodan: shodan search "port:102 Siemens"', 'Verifica segmentacion OT/IT: no debe haber rutas directas IT->OT'] }, en: { label: 'ICS/SCADA Analyzer', what: 'Analyzes the security of industrial control systems (ICS/SCADA/OT): PLCs, HMIs, historians and industrial networks.', risks: ['PLC accessible from Internet without authentication', 'Exposed insecure industrial protocol (Modbus, DNP3, BACnet)', 'Unauthorized access to control system that can cause physical damage'], verify: ['Scan OT systems with Nessus using ICS/SCADA plugins', 'Find exposed PLCs in Shodan: shodan search "port:102 Siemens"', 'Verify OT/IT network segmentation: no direct routes from IT to OT'] } } },
  { agent: 'DarkWebMonitorAgent', category: 'intelligence', severity: 'HIGH', mitre: ['T1589 - Gather Victim Identity Information', 'T1596 - Search Open Technical Databases'], tools: ['DarkOwl', 'Recorded Future', 'Cybersixgill', 'Intel 471'], content: { es: { label: 'Dark Web Monitor', what: 'Monitorea foros de la dark web, mercados clandestinos y canales de Telegram en busca de credenciales filtradas y datos de la organizacion en venta.', risks: ['Credenciales de empleados en venta en mercados dark web', 'Datos de clientes filtrados publicados en foros de hackers', 'Planes de ataque dirigidos contra la organizacion'], verify: ['Consulta Have I Been Pwned por dominio: https://haveibeenpwned.com/DomainSearch', 'Busca el dominio en DeHashed: https://dehashed.com', 'Configura alertas en servicios de monitoreo dark web'] }, en: { label: 'Dark Web Monitor', what: 'Monitors dark web forums, underground markets and Telegram channels for leaked credentials and organization data for sale.', risks: ['Employee credentials for sale in dark web markets', 'Leaked customer data posted on hacker forums', 'Conversations about planned attacks against the organization'], verify: ['Query Have I Been Pwned for corporate domain: https://haveibeenpwned.com/DomainSearch', 'Search the domain in DeHashed: https://dehashed.com', 'Set up dark web monitoring service alerts for your domain'] } } },
  { agent: 'VulnerabilityManagerAgent', category: 'analytics', severity: 'HIGH', mitre: ['T1190 - Exploit Public-Facing Application', 'T1203 - Exploitation for Client Execution'], tools: ['Nessus', 'Qualys', 'Rapid7 InsightVM', 'OpenVAS'], content: { es: { label: 'Vulnerability Manager', what: 'Gestiona el ciclo de vida completo de vulnerabilidades: descubrimiento, priorizacion por CVSS y exposicion, asignacion de remediacion y seguimiento hasta cierre.', risks: ['Vulnerabilidades criticas sin remediar durante ventanas de explotacion activa', 'Priorizacion incorrecta que deja vulnerabilidades de alto riesgo sin atender', 'Falta de visibilidad de activos que crea puntos ciegos en la cobertura'], verify: ['Ejecuta escaneo perimetral: nessus scan --target <ip-range>', 'Prioriza por CVSS v3.1: filtra CVEs con score >= 9.0 y exploit conocido', 'Verifica estado de parches: apt list --upgradable; yum check-update'] }, en: { label: 'Vulnerability Manager', what: 'Manages the complete vulnerability lifecycle: discovery, prioritization by CVSS and exposure, remediation assignment and tracking to closure.', risks: ['Critical vulnerabilities unpatched during active exploitation windows', 'Incorrect prioritization leaving high-risk vulnerabilities unaddressed', 'Lack of asset visibility creating blind spots in coverage'], verify: ['Run perimeter scan: nessus scan --target <ip-range>', 'Prioritize by CVSS v3.1: filter CVEs with score >= 9.0 and known exploit', 'Verify patch status: apt list --upgradable; yum check-update'] } } },
  { agent: 'AnomalyDetectorAgent', category: 'threats', severity: 'HIGH', mitre: ['T1082 - System Information Discovery', 'T1049 - System Network Connections Discovery'], tools: ['Elastic ML', 'Splunk ML Toolkit', 'Darktrace', 'Vectra AI'], content: { es: { label: 'Anomaly Detector', what: 'Detecta comportamientos anomalos en la red y endpoints usando modelos de machine learning. Identifica desvios estadisticos del comportamiento normal sin depender de firmas.', risks: ['Actividad sospechosa que no coincide con ninguna firma conocida', 'Volumen inusual de trafico o acceso a datos fuera del patron', 'Procesos del sistema ejecutando comportamiento inusual'], verify: ['Activa Elastic ML jobs para deteccion de anomalias: Monitor -> Machine Learning -> Jobs', 'Revisa alertas de Darktrace/Vectra en el dashboard', 'Busca desvios en metricas de baseline: CPU, red, acceso a archivos'] }, en: { label: 'Anomaly Detector', what: 'Detects anomalous behavior in network and endpoints using machine learning models. Identifies statistical deviations from normal behavior without relying on signatures.', risks: ['Suspicious activity not matching any known signature', 'Unusual volume of traffic or data access outside pattern', 'System processes exhibiting unusual behavior'], verify: ['Enable Elastic ML jobs for anomaly detection: Monitor -> Machine Learning -> Jobs', 'Review Darktrace/Vectra alerts in the dashboard', 'Look for deviations in baseline metrics: CPU, network, file access'] } } },
  { agent: 'CryptominingDetectorAgent', category: 'threats', severity: 'HIGH', mitre: ['T1496 - Resource Hijacking', 'T1059 - Command and Scripting Interpreter'], tools: ['CrowdStrike', 'Carbon Black', 'Sysmon', 'Elastic Security'], content: { es: { label: 'Cryptomining Detector', what: 'Detecta mineria de criptomonedas no autorizada en servidores y endpoints. Identifica uso inusual de CPU/GPU, procesos de mineria conocidos y conexiones a pools.', risks: ['Consumo masivo de CPU/GPU que degrada el rendimiento del sistema', 'Proceso de mineria oculto usando tecnicas de evasion', 'Servidor cloud con costos disparados por uso ilegitimo de computo'], verify: ['Monitorea uso de CPU: top -b -n 1 | head -20; busca procesos >80% CPU', 'Busca procesos de mineria conocidos: ps aux | grep -E "xmrig|minerd|cpuminer"', 'Verifica conexiones a pools de mineria: netstat -an | grep -E ":3333|:4444|:5555"'] }, en: { label: 'Cryptomining Detector', what: 'Detects unauthorized cryptocurrency mining on servers and endpoints. Identifies unusual CPU/GPU usage, known mining processes and pool connections.', risks: ['Massive CPU/GPU consumption degrading system performance', 'Hidden mining process using evasion techniques', 'Cloud server with soaring costs from illegitimate compute usage'], verify: ['Monitor CPU usage: top -b -n 1 | head -20; look for processes >80% CPU', 'Search for known mining processes: ps aux | grep -E "xmrig|minerd|cpuminer"', 'Verify connections to mining pools: netstat -an | grep -E ":3333|:4444|:5555"'] } } },
  { agent: 'FilelessMalwareDetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1059.001 - PowerShell', 'T1055 - Process Injection', 'T1620 - Reflective Code Loading'], tools: ['Sysmon', 'CrowdStrike', 'Carbon Black', 'Volatility'], content: { es: { label: 'Fileless Malware', what: 'Detecta malware sin archivos (fileless) que opera completamente en memoria: PowerShell ofuscado, reflective DLL injection, living-off-the-land y process hollowing.', risks: ['Malware en memoria que no deja artefactos en disco para antivirus', 'PowerShell con payloads codificados en base64 que evaden deteccion', 'Process injection en procesos legitimos del sistema (svchost, explorer)'], verify: ['Activa script block logging en PowerShell: Event ID 4104', 'Monitorea process injection: Sysmon Event ID 8 (CreateRemoteThread)', 'Analiza memoria con Volatility: vol.py -f memory.dmp --profile=Win10x64 malfind'] }, en: { label: 'Fileless Malware', what: 'Detects fileless malware operating entirely in memory: obfuscated PowerShell, reflective DLL injection, living-off-the-land and process hollowing.', risks: ['In-memory malware leaving no disk artifacts for antivirus to detect', 'PowerShell with base64-encoded payloads evading detection', 'Process injection into legitimate system processes (svchost, explorer)'], verify: ['Enable PowerShell script block logging: Event ID 4104', 'Monitor process injection: Sysmon Event ID 8 (CreateRemoteThread)', 'Analyze memory with Volatility: vol.py -f memory.dmp --profile=Win10x64 malfind'] } } },
  { agent: 'SocialEngineeringDetectorAgent', category: 'threats', severity: 'HIGH', mitre: ['T1566 - Phishing', 'T1598 - Spearphishing for Info', 'T1204 - User Execution'], tools: ['Proofpoint', 'Mimecast', 'Microsoft Defender for Office 365', 'PhishER'], content: { es: { label: 'Social Engineering', what: 'Detecta intentos de ingenieria social: phishing por email, vishing, smishing, pretexting y Business Email Compromise (BEC).', risks: ['BEC (Business Email Compromise) que solicita transferencias fraudulentas', 'Phishing dirigido que roba credenciales de acceso VPN/Office365', 'Vishing suplantando al soporte tecnico para obtener acceso'], verify: ['Analiza headers de email sospechoso: revisa SPF/DKIM/DMARC', 'Verifica el dominio remitente: whois | grep Creation Date (dominios recientes son sospechosos)', 'Comprueba si el adjunto es malicioso: hash en VirusTotal'] }, en: { label: 'Social Engineering', what: 'Detects social engineering attempts: email phishing, vishing, smishing, pretexting and Business Email Compromise (BEC).', risks: ['BEC (Business Email Compromise) requesting fraudulent transfers', 'Targeted phishing stealing VPN/Office365 credentials', 'Vishing impersonating tech support to gain access'], verify: ['Analyze suspicious email headers: check SPF/DKIM/DMARC', 'Verify sender domain: whois | grep Creation Date (recent domains are suspicious)', 'Check if attachment is malicious: hash in VirusTotal'] } } },
  { agent: 'SupplyChainAttackDetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1195 - Supply Chain Compromise', 'T1554 - Compromise Client Software Binary'], tools: ['Snyk', 'Sonatype Nexus IQ', 'JFrog Xray', 'GitHub Advanced Security'], content: { es: { label: 'Supply Chain Attack', what: 'Detecta ataques a la cadena de suministro de software: dependencias comprometidas, paquetes maliciosos (typosquatting en npm/PyPI) y binarios troyanizados.', risks: ['Dependencia npm/pip/maven comprometida con malware (typosquatting)', 'Actualizacion de software que incluye codigo malicioso', 'Binario firmado digitalmente pero con payload malicioso insertado'], verify: ['Escanea dependencias: snyk test; npm audit; pip check', 'Verifica hashes de binarios criticos contra valores conocidos', 'Monitorea alertas de seguridad de repositorios: GitHub Security Advisories'] }, en: { label: 'Supply Chain Attack', what: 'Detects software supply chain attacks: compromised dependencies, malicious packages (typosquatting in npm/PyPI) and trojaned binaries.', risks: ['npm/pip/maven dependency compromised with malware (typosquatting)', 'Software update including malicious code', 'Digitally signed binary with malicious payload inserted'], verify: ['Scan dependencies: snyk test; npm audit; pip check', 'Verify hashes of critical binaries against known values', 'Monitor repository security alerts: GitHub Security Advisories'] } } },
  { agent: 'ZeroDayDetectorAgent', category: 'threats', severity: 'CRITICAL', mitre: ['T1190 - Exploit Public-Facing Application', 'T1211 - Exploitation for Defense Evasion'], tools: ['Darktrace', 'Vectra AI', 'CrowdStrike Falcon', 'Palo Alto Cortex XDR'], content: { es: { label: 'Zero-Day Detector', what: 'Detecta explotacion de vulnerabilidades zero-day (desconocidas y sin parche). Usa analisis de comportamiento y anomalias para identificar exploits novedosos.', risks: ['Explotacion de vulnerabilidad desconocida sin parche disponible', 'Bypass de controles de seguridad existentes mediante tecnica nueva', 'Tiempo de exposicion prolongado hasta que el vendor libere un parche'], verify: ['Monitorea crashes y errores inesperados en aplicaciones criticas', 'Busca actividad de post-explotacion: nuevas cuentas, persistence, C2', 'Activa sandboxing de archivos entrantes: cualquier ejecutable se analiza antes de correr'] }, en: { label: 'Zero-Day Detector', what: 'Detects exploitation of zero-day vulnerabilities (unknown and unpatched). Uses behavioral analysis and anomalies to identify novel exploits.', risks: ['Exploitation of unknown vulnerability with no available patch', 'Bypass of existing security controls via new technique', 'Prolonged exposure time until vendor releases a patch'], verify: ['Monitor crashes and unexpected errors in critical applications', 'Look for post-exploitation activity: new accounts, persistence, C2', 'Enable sandboxing of incoming files: any executable is analyzed before running'] } } },
]

const STATIC_MAP = new Map<string, StaticDoc>(STATIC_DOCS.map(d => [d.agent, d]))

const PRIORITY_TO_SEV: Record<string, 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'> = {
  CRITICAL: 'CRITICAL', HIGH: 'HIGH', MEDIUM: 'MEDIUM', LOW: 'LOW',
}

const SEV_STYLES: Record<string, string> = {
  CRITICAL: 'bg-red-500/10 text-red-400 border border-red-500/30',
  HIGH:     'bg-orange-500/10 text-orange-400 border border-orange-500/30',
  MEDIUM:   'bg-yellow-500/10 text-yellow-400 border border-yellow-500/30',
  LOW:      'bg-green-500/10 text-green-400 border border-green-500/30',
}

type LangKey = 'es' | 'en'

export default function DocsPage() {
  const { t, lang } = useTranslation()
  const [agents, setAgents] = useState<AgentInfo[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState<string>('all')
  const [expanded, setExpanded] = useState<string | null>(null)

  const cl = (lang === 'es' ? 'es' : 'en') as LangKey

  useEffect(() => {
    getAgents()
      .then(data => {
        const list = (data as { agents?: AgentInfo[] }).agents ?? []
        setAgents(list)
      })
      .catch(() => setAgents([]))
      .finally(() => setLoading(false))
  }, [])

  const categories = useMemo(() => {
    const cats = new Set(agents.map(a => a.category))
    return Array.from(cats).sort()
  }, [agents])

  const filtered = useMemo(() => {
    const q = search.toLowerCase()
    return agents.filter(a => {
      const staticLabel = STATIC_MAP.get(a.name)?.content[cl].label ?? ''
      const matchSearch = !q
        || (a.name ?? '').toLowerCase().includes(q)
        || (a.description ?? '').toLowerCase().includes(q)
        || staticLabel.toLowerCase().includes(q)
      const matchCat = category === 'all' || a.category === category
      return matchSearch && matchCat
    })
  }, [agents, search, category, cl])

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-white">{t('docs.title')}</h1>
        <p className="text-slate-400 text-sm mt-1">{t('docs.subtitle')}</p>
      </div>

      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
          <input
            type="text"
            placeholder={t('docs.searchPlaceholder')}
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="w-full bg-surface border border-border rounded-lg pl-10 pr-4 py-2.5 text-sm text-white placeholder:text-slate-500 focus:outline-none focus:border-accent transition-colors"
          />
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            onClick={() => setCategory('all')}
            className={`px-3 py-2 rounded-lg text-xs font-medium transition-colors ${category === 'all' ? 'bg-accent/20 text-accent border border-accent/40' : 'bg-surface border border-border text-slate-400 hover:border-accent/40 hover:text-accent'}`}
          >
            {t('docs.allCategories')} {agents.length > 0 && `(${agents.length})`}
          </button>
          {categories.map(cat => {
            const count = agents.filter(a => a.category === cat).length
            return (
              <button
                key={cat}
                onClick={() => setCategory(cat)}
                className={`px-3 py-2 rounded-lg text-xs font-medium transition-colors ${category === cat ? 'bg-accent/20 text-accent border border-accent/40' : 'bg-surface border border-border text-slate-400 hover:border-accent/40 hover:text-accent'}`}
              >
                {t(`docs.categories.${cat}`) || cat.replace(/_/g, ' ')} ({count})
              </button>
            )
          })}
        </div>
      </div>

      {loading && (
        <div className="flex items-center justify-center py-16 gap-3 text-slate-400">
          <Loader2 className="w-5 h-5 animate-spin" />
          <span className="text-sm">{t('common.loading')}</span>
        </div>
      )}

      {!loading && filtered.length === 0 && (
        <div className="text-center py-16 text-slate-500 text-sm">{t('docs.noResults')}</div>
      )}

      <div className="space-y-2">
        {filtered.map(agent => {
          const staticDoc = STATIC_MAP.get(agent.name)
          const catDefaults = CAT_DEFAULTS[agent.category] ?? CAT_DEFAULTS.threats
          const severity = PRIORITY_TO_SEV[agent.priority] ?? 'MEDIUM'
          const label = staticDoc?.content[cl].label ?? agent.name.replace(/Agent$/, '').replace(/([A-Z])/g, ' $1').trim()
          const what = staticDoc?.content[cl].what ?? agent.description
          const risks = staticDoc?.content[cl].risks ?? catDefaults[cl].risks
          const verify = staticDoc?.content[cl].verify ?? catDefaults[cl].verify
          const mitre = staticDoc?.mitre ?? catDefaults.mitre
          const tools = staticDoc?.tools ?? catDefaults.tools
          const isOpen = expanded === agent.name
          const hasDetail = !!staticDoc

          return (
            <div key={agent.name} className="bg-surface border border-border rounded-xl overflow-hidden">
              <button
                className="w-full flex items-center justify-between px-5 py-3.5 hover:bg-white/5 transition-colors"
                onClick={() => setExpanded(isOpen ? null : agent.name)}
              >
                <div className="flex items-center gap-3">
                  <div className={`w-7 h-7 rounded-lg flex items-center justify-center shrink-0 ${hasDetail ? 'bg-accent/10 border border-accent/20' : 'bg-slate-700/40 border border-slate-600/20'}`}>
                    <Shield className={`w-3.5 h-3.5 ${hasDetail ? 'text-accent' : 'text-slate-500'}`} />
                  </div>
                  <div className="text-left">
                    <p className="text-sm font-semibold text-white">{label}</p>
                    <p className="text-xs text-slate-500 font-mono">{agent.name}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <span className={`px-2 py-0.5 rounded text-xs font-bold ${SEV_STYLES[severity]}`}>{severity}</span>
                  <span className="text-xs text-slate-600 hidden sm:block">{agent.category.replace(/_/g, ' ')}</span>
                  {isOpen ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
                </div>
              </button>

              {isOpen && (
                <div className="border-t border-border px-5 py-5 space-y-4">
                  <div>
                    <div className="flex items-center gap-2 mb-1.5">
                      <Shield className="w-3.5 h-3.5 text-accent" />
                      <p className="text-xs font-semibold text-accent uppercase tracking-wider">{t('docs.whatItDoes')}</p>
                    </div>
                    <p className="text-sm text-slate-300 leading-relaxed">{what}</p>
                  </div>

                  <div>
                    <div className="flex items-center gap-2 mb-1.5">
                      <AlertTriangle className="w-3.5 h-3.5 text-orange-400" />
                      <p className="text-xs font-semibold text-orange-400 uppercase tracking-wider">{t('docs.detectedRisks')}</p>
                    </div>
                    <ul className="space-y-1">
                      {risks.map((r, i) => (
                        <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
                          <span className="text-orange-400 mt-0.5 shrink-0">▸</span>{r}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div>
                    <div className="flex items-center gap-2 mb-1.5">
                      <Terminal className="w-3.5 h-3.5 text-green-400" />
                      <p className="text-xs font-semibold text-green-400 uppercase tracking-wider">{t('docs.manualVerification')}</p>
                    </div>
                    <div className="space-y-1.5">
                      {verify.map((v, i) => (
                        <div key={i} className="bg-background rounded-lg px-3 py-2">
                          <p className="text-xs text-slate-300 font-mono leading-relaxed">{v}</p>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div className="flex flex-wrap gap-4">
                    {mitre && mitre.length > 0 && (
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1.5">{t('docs.mitreTactics')}</p>
                        <div className="flex flex-wrap gap-1.5">
                          {mitre.map((m, i) => (
                            <span key={i} className="px-2 py-0.5 rounded bg-purple-500/10 text-purple-400 border border-purple-500/20 text-xs font-mono">{m}</span>
                          ))}
                        </div>
                      </div>
                    )}
                    {tools && tools.length > 0 && (
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-1.5 mb-1.5">
                          <Wrench className="w-3 h-3 text-slate-400" />
                          <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider">{t('docs.usefulTools')}</p>
                        </div>
                        <div className="flex flex-wrap gap-1.5">
                          {tools.map((tool, i) => (
                            <span key={i} className="px-2 py-0.5 rounded bg-slate-700/50 text-slate-300 border border-slate-600/30 text-xs">{tool}</span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}
